version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.2.26
    environment:
    - DB_USER=invoiceplane
    - DB_PASS=password
    - DB_NAME=invoiceplane_db
    volumes:
    - /srv/docker/invoiceplane/mysql:/var/lib/mysql

  invoiceplane:
    service_name: invoiceplane
    restart: always
    build:
      context: .
    command: app:invoiceplane
    environment:
    - DEBUG=false
    - TZ=Europe/Paris

    - DB_TYPE=mysqli
    - DB_HOST=mysql
    - DB_USER=invoiceplane
    - "DB_PASS={{invoiceplane_db_password}}"
    - DB_NAME=invoiceplane_db

    - INVOICEPLANE_URL=http://localhost:10080
    - INVOICEPLANE_PROXY_IPS=
    - INVOICEPLANE_BACKUPS_EXPIRY=0
    depends_on:
    - mysql
    volumes:
    - /srv/docker/invoiceplane/invoiceplane:/var/lib/invoiceplane

  nginx:
    restart: always
    build:
      context: .
    command: app:nginx
    environment:
    - INVOICEPLANE_PHP_FPM_HOST=invoiceplane
    - INVOICEPLANE_PHP_FPM_PORT=6000
    depends_on:
    - invoiceplane
    ports:
    - "10080:80"
    volumes_from:
    - invoiceplane
